development:
  adapter: sqlite3
  database: db/salad.sqlite3
  pool: 5
  timeout: 5000
  
development2:
  adapter: mysql
  database: salad
  username: root
  password:
  host: localhost
  socket: /opt/local/var/run/mysql5/mysqld.sock
 
test:
  adapter: mysql
  database: salad_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: salad
  username: lightsalad
  password: salad
  host: localhost
